# Generated by Django 4.1 on 2022-08-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0002_remove_myuser_username_alter_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Salary',
            field=models.IntegerField(default=0),
        ),
    ]
