# Generated by Django 4.1 on 2022-08-31 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0003_profile_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Salary',
            new_name='salary',
        ),
    ]
