# Generated by Django 4.1 on 2022-09-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(default='2', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='secret',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
